global:
  imagePullSecrets:
    - name: dockerhub
  storageClass: "do-block-storage"
  redis:
    password: "password"
persistence:
  enabled: true
  size: 1Gi
image:
  repository: "avshyd/redismods-cluster"
  tag: latest
metrics:
  enabled: false
volumePermissions:
  enabled: false
