global:
  imagePullSecrets:
    - name: dockerhub
  storageClass: "do-block-storage"
  redis:
    password: "password"
persistence:
  enabled: true
  size: 1Gi
redis:
  args: [ "--loadmodule", "/opt/bitnami/redis/modules/redisai.so", "--loadmodule", "/opt/bitnami/redis/modules/redisearch.so", "--loadmodule", "/opt/bitnami/redis/modules/redisgraph.so", "--loadmodule", "/opt/bitnami/redis/modules/redistimeseries.so", "--loadmodule", "/opt/bitnami/redis/modules/rejson.so", "--loadmodule", "/opt/bitnami/redis/modules/redisbloom.so", "--loadmodule", "/opt/bitnami/redis/modules/redisgears.so", "Plugin", "/var/opt/redislabs/modules/rg/plugin/gears_python.so" ]
metrics:
  enabled: false
volumePermissions:
  enabled: false
