version: '3.1'

services:
  elasticsearch:
    image: elasticsearch:8.3.1
    restart: always
    environment:
      "discovery.type": "single-node"
      "http.cors.enabled": true
      "http.cors.allow-origin": "http://localhost:8080,*"
      "http.cors.allow-methods": OPTIONS, HEAD, GET, POST, PUT, DELETE
      "http.cors.allow-headers": X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      "xpack.security.enabled": false
      ELASTIC_PASSWORD: "password"
      KIBANA_PASSWORD: "password"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: kibana:8.3.1
    restart: always
    environment:
      SERVERNAME: "kibana"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: "password"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./kibanadata:/usr/share/kibana/data
    networks:
      - elastic
networks:
  elastic:
    name: "elastic"
    driver: bridge
